In [166]:
import pandas as pd
import numpy as np

In [167]:
def prediction(ra_input,coeff_parameter):
    prediction_output = coeff_parameter[0]
    for j in range(0,len(ra_input)-1):
        prediction_output = prediction_output + (ra_input[j]*coeff_parameter[j+1])
    return prediction_output
            
        
    
       

In [168]:
def sgd_to_get_coeff_parameter(train_data,lrate,coeff_parameter,epoc):
    while(epoc>0):
        for data in range(0,len(train_data)):
            ra_data=np.array(train_data[data])
            coeff_parameter = np.array(coeff_parameter)
            yout = prediction(ra_data,coeff_parameter)
            error = yout-ra_data[len(ra_data)-1]
            print coeff_parameter
            coeff_parameter[0] = coeff_parameter[0]- (lrate*error)
            for i in range(1,len(coeff_parameter)):
                coeff_parameter[i] = coeff_parameter[i] - (lrate*error*ra_data[i-1])
        epoc=epoc-1
    return coeff_parameter
    

In [169]:
train_data = np.array([[1,2,1],[2,4,2],[3,4,3],[5,4,6],[1,3,5]])
#train_data = np.array([[1,1],[2,3],[3,3],[4,2],[5,5]])
number_of_coeff = len(train_data[0])
coeff_parameter = []
for i in range(0,number_of_coeff):
    coeff_parameter.append(0.0)
lrate = 0.01
epoc =  4
coeff_parameter=sgd_to_get_coeff_parameter(train_data,lrate,coeff_parameter,epoc)

print coeff_parameter

[0. 0. 0.]
[0.01 0.01 0.02]
[0.0289 0.0478 0.0956]
[0.053353 0.121159 0.193412]
[0.09902504 0.3495192  0.37610016]
[0.13325659 0.38375075 0.47879482]
[0.12851062 0.37900478 0.46930288]
[0.12087331 0.36373015 0.43875361]
[0.12120252 0.3647178  0.44007048]
[0.14415179 0.47946413 0.53186754]
[0.1719596  0.50727194 0.61529099]
[0.16286147 0.49817381 0.59709472]
[0.14738559 0.46722205 0.5351912 ]
[0.14048742 0.44652755 0.50759854]
[0.15645223 0.52635159 0.57145776]
[0.18248046 0.55237982 0.64954245]
[0.17214101 0.54204036 0.62886355]
[0.15442425 0.50660685 0.55799651]
[0.14536194 0.47941992 0.52174728]
[0.15906743 0.54794739 0.57656925]
[0.18470021 0.57358016 0.65346757]


In [170]:
#test_data = np.array([[1,1],[2,3],[3,3],[4,2],[5,5]])
test_data = np.array([[1,2,1],[2,4,2],[3,4,3],[5,4,6],[1,3,5]])
print coeff_parameter
mean_square_error = 0.0
for i in range(0,len(test_data)):
    ra_data=test_data[i]
    yout = prediction(ra_data,coeff_parameter)
    error = yout-ra_data[len(ra_data)-1]
    mean_square_error = mean_square_error + (error**2)
    print("Actual output %s : Predicted data %s\n"%(ra_data[len(ra_data)-1],yout))
    
print("mean_square_error %s",(mean_square_error/(len(test_data))))


[0.18470021 0.57358016 0.65346757]
Actual output 1 : Predicted data 2.0652155176158495

Actual output 2 : Predicted data 3.945730827558466

Actual output 3 : Predicted data 4.5193109898048665

Actual output 6 : Predicted data 5.666471314297668

Actual output 5 : Predicted data 2.7186830914639573

('mean_square_error %s', 2.5089013314763142)
